export default {
    loading: false,
    step: 1,
    date: "",
    modal: false,
    // disableButton: false,
    counterAlert: 0,
    familyDefault: {
        full_name: "",
        kinship_id: "",
        date_birth: "",
    },
    family: {
        full_name: "",
        kinship_id: "",
        date_birth: "",
    },
    academicDefault: {
        academic_level_id: "",
        education_center: "",
        year: "",
        obtained_title: "",
    },
    academic: {
        academic_level_id: "",
        education_center: "",
        year: "",
        obtained_title: "",
    },
    dialog: false,
    dialogWork: false,
    familyStatus: [],
    professions: [],
    departments: [],
    municipalities: [],
    vulnerableArea: [],
    directions: [],
    subdirections: [],
    units: [],
    kinships: [],
    academicLevels: [],
    academics: [],
    families: [],

    employee: {
        full_name: "",
        family_status_name: "",
        profession_name: "",
        current_address: "",
        department_name: "",
        municipality_name: "",
        personal_email: "",
        phone: "",
        cell_phone: "",
        vulnerableArea: "",
        direction_name: "",
        subdirection_name: "",
        unit_name: "",
        nominal_fee: "",
        functional_position: "",
        immediate_superior: "",
        email_institutional: "",
        municipality_assigned_id: "",
        department_assigned_id: "",
        emergency_full_name: "",
        emergency_kinship_id: "",
        emergency_phone: "",
        emergency_cell_phone: "",
        subjects_approved: "",
        dui_file: "",
        title_file: "",
        idSection: 1,
    },
    showAlert: false,
    textAlert: "",
    alertEvent: "success",
    showStudies: false,
    alertTimeOut: 0,
    counterEconomicsActivities: 0,

    // flagsNotification: {
    //     studies: false,
    //     works: false,
    //     recognitions: false,
    //     disabilities: false,
    //     dependents: false,
    // },
};
